services:
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    ports:
      - "4321:4321"
    volumes:
      - .:/app
    working_dir: /app/apps/frontend
    command: sh -c "pnpm install && pnpm dev --host"
    depends_on:
      - directus
    networks:
      - directus-net

  directus:
    build:
      context: .
      dockerfile: apps/cms/Dockerfile
    restart: unless-stopped
    ports:
      - "8055:8055"
    volumes:
      - ./volumes/directus-uploads:/directus/uploads
    env_file:
      - .env
    environment:
      - DB_CLIENT=${DB_CLIENT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - PUBLIC_URL=${PUBLIC_URL}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SECRET=${SECRET}
      - STORAGE_LOCATIONS=${STORAGE_LOCATIONS}
      - STORAGE_LOCAL_DRIVER=${STORAGE_LOCAL_DRIVER}
      - STORAGE_LOCAL_ROOT=${STORAGE_LOCAL_ROOT}
      - TELEMETRY=${TELEMETRY}
    networks:
      - directus-net

networks:
  directus-net:
    external: true
